<?php

namespace nk\ExamBundle\Entity;

use Doctrine\ORM\EntityRepository;
use nk\UserBundle\Entity\User;

/**
 * IgnoredExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IgnoredExamRepository extends EntityRepository
{
    public function unignore($unit, User $user)
    {
        $this->createQueryBuilder('i')
            ->delete()
            ->where('i.unit = :unit')
            ->andWhere('i.user = :user')
            ->setParameter('unit', $unit)
            ->setParameter('user', $user)
            ->getQuery()
            ->execute();
    }
}
