<?php

namespace nk\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.id', 'DESC');
    }

    public function findAdmins()
    {
        return $this->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', '%ROLE_ADMIN%')
            ->getQuery()
            ->getResult();
    }

    public function findAllUsernames()
    {
        $r = $this->createQueryBuilder('u')
            ->select('u.username username')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        $r = array_map(function($e){
            return $e['username'];
        }, $r);

        return $r;
    }
}
